
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: transactions
    description: "transactions on the system"
    columns:
      - name: date
        description: "The date of the transaction"
        data_tests:
          - not_null
          - unique

      - name: time
        description: "The time of the transaction"
        data_tests:
          - not_null

      - name: order_no
        description: "The order number"
        data_tests:
          - not_null

      - name: account_no
        description: "The account number"
        data_tests:
          - not_null

      - name: account_id
        description: "The account ID"
        data_tests:
          - not_null

      - name: type
        description: "The type of the transaction"
        data_tests:
          - not_null
          - unique

      - name: description
        description: "The item or payment type"
        data_tests:
          - not_null

      - name: detail
        description: "Additional Info"
        data_tests:
          - not_null

      - name: information
        description: "ASSESS THIS FIELD"
        data_tests:
          - not_null

      - name: quantity
        description: "The quantity of an item selected"
        data_tests:
          - not_null

      - name: sales_amount
        description: "The cost of the transaction"
        data_tests:
          - not_null
          - unique

      - name: discount
        description: "The value of discount applied to the sales amount"
        data_tests:
          - not_null

      - name: VAT
        description: "The vat applied to the transaction"
        data_tests:
          - not_null

      - name: payment_amount
        description: "The amount payed by the customer"
        data_tests:
          - not_null
      
      - name: change
        description: "The change given to the customer"
        data_tests:
          - not_null


      




  - name: payments
    description: "a list of payments made by customers"
    columns:
      - name: date
        description: "The date the payment was made"
        data_tests:
          - not_null

      - name: time
        description: "The time the payment was made"
        data_tests:
          - not_null

      - name: account_id
        description: "The unique identifier for the transaction"
        data_tests:
          - not_null

      - name: terminal_id
        description: "The terminal where the payment was made"
        data_tests:
          - not_null

      - name: employee
        description: "The employee who processed the payment"
        data_tests:
          - not_null

      - name: payment_amount
        description: "The amount of the payment"
        data_tests:
          - not_null
