version: 2

sources:
  - name: source_db
    description: "Raw data from the PostgreSQL database."
    database: source_db
    schema: public
    tables:
      - name: transactions
        description: "List of transactions"